server:
    port: 8083
spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/db_notification
        username: myuser
        password: mypassword
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true